#!/bin/sh
set -o errexit -o nounset

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
USER="$(whoami)"

readonly SCRIPT_DIR USER
readonly TARGET="Launchterm"
readonly DOMAIN="com.msanders.Launchterm"
readonly SUPPORT_DIR="$HOME/Library/Application Support/$TARGET"
readonly AGENT_DIR="$HOME/Library/LaunchAgents"
readonly PLIST="$AGENT_DIR/$DOMAIN.plist"

mkdir -p "$SUPPORT_DIR"
mkdir -p "$AGENT_DIR"

(
    cd "$SCRIPT_DIR"
    echo "Building Launchterm..."
    swift build -c release -Xswiftc -Osize
    cp .build/release/Launchterm "$SUPPORT_DIR/$TARGET"
    strip "$SUPPORT_DIR/$TARGET"
    sed -e "s/{USER}/$USER/" "$SCRIPT_DIR/$DOMAIN.template.plist" > "$PLIST"

    if launchctl list | grep -Fq "$DOMAIN"; then
        launchctl unload "$PLIST"
    fi

    launchctl load "$PLIST"
    echo "Installed $TARGET."
    swift package clean
)
